

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * feedback.java
 *
 * Created on Oct 11, 2017, 10:09:07 AM
 */

/**
 *
 * @author DELL pc
 */
public class feedback extends javax.swing.JFrame {

    /** Creates new form feedback */
    public feedback() {
        initComponents();
         Toolkit tk=getToolkit();
       Dimension size=tk.getScreenSize();
       setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2); getContentPane().setBackground(new Color(0,153,225));
   currentDate();
    }

    public void currentDate(){
            Calendar cal=new GregorianCalendar();
      int month=cal.get(Calendar.MONTH);
      int day=cal.get(Calendar.DAY_OF_MONTH);
      int year=cal.get(Calendar.YEAR);
      date.setText(""+(month+1)+"/"+day+"/"+year);
 date.setText(""+year+"/"+(month+1)+"/"+day); 
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel47 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        jLabel329 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        rating = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        jButton73 = new javax.swing.JButton();
        jLabel330 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setBackground(new java.awt.Color(204, 255, 255));
        jLabel47.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48));
        jLabel47.setForeground(new java.awt.Color(204, 0, 51));
        jLabel47.setText("<HTML>YOUR VALUABLE <br>   <CENTER>FEEDBACKS");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 390, 120));

        jLabel239.setBackground(new java.awt.Color(255, 255, 0));
        jLabel239.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel239.setForeground(new java.awt.Color(0, 0, 153));
        jLabel239.setText("    Name");
        jLabel239.setOpaque(true);
        getContentPane().add(jLabel239, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 230, 50));

        jLabel327.setBackground(new java.awt.Color(255, 255, 0));
        jLabel327.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel327.setForeground(new java.awt.Color(0, 0, 153));
        jLabel327.setText("    DATE");
        jLabel327.setOpaque(true);
        getContentPane().add(jLabel327, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 230, 50));

        jLabel329.setBackground(new java.awt.Color(255, 255, 0));
        jLabel329.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel329.setForeground(new java.awt.Color(0, 0, 153));
        jLabel329.setText("  RATINGS");
        jLabel329.setOpaque(true);
        getContentPane().add(jLabel329, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 230, 50));

        jLabel48.setBackground(new java.awt.Color(255, 255, 0));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel48.setForeground(new java.awt.Color(0, 0, 153));
        jLabel48.setText(" FEEDBACK");
        jLabel48.setOpaque(true);
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 240, 120));

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea5.setRows(5);
        jScrollPane2.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 310, 170));

        rating.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 150, 50));

        date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date.setEnabled(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 260, 60));

        q2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 260, 50));

        jButton73.setBackground(new java.awt.Color(255, 255, 0));
        jButton73.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jButton73.setForeground(new java.awt.Color(0, 153, 204));
        jButton73.setText("Submit");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 230, 110));

        jLabel330.setBackground(new java.awt.Color(255, 255, 0));
        jLabel330.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel330.setForeground(new java.awt.Color(0, 0, 153));
        jLabel330.setText("(1- 5)");
        jLabel330.setOpaque(true);
        getContentPane().add(jLabel330, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 130, 50));

        jLabel208.setBackground(new java.awt.Color(255, 255, 0));
        jLabel208.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel208.setForeground(new java.awt.Color(0, 0, 153));
        jLabel208.setText("<html>IN LESS THAN<br> <center>30 WORDS");
        jLabel208.setOpaque(true);
        getContentPane().add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, 150));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 130, 110));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Cool-Wallpapers-Hd-23.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dateActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/farmer","root","root");
            Statement st=con.createStatement();
            String a,b,c,d,e,f,sql;
             b=q2.getText();
            d=date.getText();
            e=rating.getText();
            f=jTextArea5.getText();
            sql="insert into feedback values('"+b+"','"+d+"','"+e+"','"+f+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"THANKS FOR YOUR FEEDBACK");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Enter the Details");}



        //select





       
   
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new NavBharat().setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton73;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField rating;
    // End of variables declaration//GEN-END:variables

}
